# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
 Item.create(title: "Mizuno ST180 Driver", description: "Built for raw power and launch – the ST180 driver is a real game changer. Designed to rip it, not having an infinite track allows us to push even more mass lower and forward into the head for super low spins. Combined with the SP700 Titanium face, the Shockwave Sole produces raw power and explosive ball speeds. Simply put, it was engineered to go fast and long.", price: 500, image_url: "drivers.jpg", category: "drivers", brand: "Mizuno")
 Item.create(title: "Speedblade iron", description: "If you are after a set of irons that provide forgiveness and playability, then look no further than these exceptional Speedblade irons. Thanks to each iron being individually designed, they offer great distance gapping, while the lower irons bridge the gap between your irons and fairway woods. These irons are very easy to launch high, allowing the ball to come down on a steeper decent to help you hit more greens.", price: 300, image_url: "irons.jpg", category: "irons", brand: "Taylormade")
 Item.create(title: "Ping G30 Fairway Wood", description: "Increased ball speed is achieved in the PING G30 Fairway Wood through a hotter face without sacrificing high launch or consistency. The face is engineered using Carpenter 475 steel, a material 44 percent stronger than 17-4 stainless steel. The face profile provides an inspirational appearance while increasing its height for additional face bending and forgiveness. The G30 fairway woods offer progressive CG positions to maximise distance.", price: 250, image_url: "woods.jpg", category: "woods", brand: "Ping")
 Item.create(title: "Titleist Premium Carry Bag", description: "This lightweight and compact carry bag is perfect for carrying if weight savings are at a premium. This bag has a unique top cuff design, with 3-way organiser dividers and mini legs built-in to the top, plus has a StaDry waterproof material bottom and underside to protect your gear from any moisture. For a comfortable carry the bag weighs just 1.2 kilograms and has a convertible strap .", price: 108, image_url: "accessories.jpg", category: "Accessories", brand: "Titlest")